spring.application.name=cozyHome-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/cozyhome_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect